---
title: What about children's wellbeing? Framing active school travel in Ontario, Canada
author:
  # see ?rjournal_article for more information
  - name: Elise Desjardins
    affiliation: School of Earth, Environment & Society, McMaster University
    address:
    - 1280 Main Street West, Hamilton, ON L8S 4L8
    email: desjae@mcmaster.ca
  - name: Jason Lam
    email: lamj54@mcmaster.ca
    affiliation: Affiliation 1
    address:
    - line 1 affiliation 1
  - name: Owen Waygood
    affiliation: University Polytechnique de Montreal
    email: owen.waygood@polymtl.ca
    address:
    - Montreal, QC
  - name: Antonio Paez
    email: paezha@mcmaster.ca
    affiliation: Affiliation 1
    address:
    - line 1 affiliation
abstract: >
  An abstract of less than 200 words.
preamble: |
  % Any extra LaTeX you need in the preamble

journal: "Journal of School Health"
date: "`r Sys.Date()`"
bibliography: References.bib
#linenumbers: true
#numbersections: true
output: rticles::rjournal_article
---

# Background 

Walking and cycling to school, commonly known as active school travel or active school transportation (AST) has been declining in Canada and North America for decades [@rothmanDeclineActiveSchool2018], with levels much lower than other developed countries like The Netherlands [@vangoeverdenSchoolTravelBehaviour2013] and Japan [@waygoodChapterSixteenJapan2020]. This trend has prompted an abundance of worlwide research over the past two decades to examine why fewer children are walking and cycling to school, what influences AST, and the associated implications for children's health. Many studies have been specific to Canada [*inter alia*, see: @buliungActiveSchoolTransportation2009; @faulknerSchoolTravelChildren2013; @mammenUnderstandingDriveEscort2012; @mammenSchoolTravelPlanning2014; @rothmanActiveSchoolTransportation2021; @wilsonUnderstandingChildParent2018] which aligns with and informs a growing interest in increasing active school travel levels. Indeed, a diversity of stakeholders responsible for transportation, public health, and education are collaborating and spearheading efforts to get more children walking and cycling. Promoting AST is seen as an affordable, convenient, and environmentally friendly way to enhance the mental, physical, and psychological health of children [@mammenSchoolTravelPlanning2014]. These goals should be clearly articulated and reflected in transportation plans and policies to guide initiatives, but there is research lacking that specifically explores how Canadian municipalities and schools frame and discuss AST with the public. 

## Literature Review

Several recent reviews offer a comprehensive synopsis of the state of active school travel [@ikedaAssociationsChildrenActive2018; @rothmanDeclineActiveSchool2018; @schoeppeAssociationsChildrenIndependent2013], while others assess the efficacy of interventions and strategies that have been implemented to encourage and support AST [@buttazzoniActiveSchoolTravel2018; @chillonSystematicReviewInterventions2011; @jonesInterventionsPromotingActive2019; @laroucheEffectivenessActiveSchool2018; @marziInterventionsAimingPromote2020; @schonbachStrategiesEffectsSchoolbased2020]. Many patterns emerge from studies within and between countries with respect to the factors that are positively associated with AST. These factors broadly fall into distinct categories: individual, household, social environment, and physical environment. Among the most influential are age, gender, distance to school, parental perceptions of the environment [@demeesterParentalPerceivedNeighborhood2014] and children's skills [@ghekiereInsightsChildrenIndependent2017], quality of the built environment, and urban infrastructure. The consensus is that these factors are interrelated and that interventions ought to target multiple factors in order to increase walking and cycling levels to school. More recently, researchers have been exploring the link between transportation and children's wellbeing [@waygoodTransportChildrenWellbeing2020], which has relevant applications to the study of school travel and satisfaction [see @vandenbergFactorsAffectingParental2020] among others. 

Furthermore, AST is one of the most common opportunities for children to travel without adult supervision on a regular basis. CIM was first described by Hillman et al. [-@hillmanOneFalseMove1990] as the freedom of children to travel and play within their neighborhood and city without the presence of adults. Similar to AST, children's independent mobility (CIM) is much less common than it was for previous generations [@bhosaleIntergenerationalChangeChildren2017], and is influenced by related personal and environmental factors [@marziChildrenIndependentMobility2018]. CIM is particularly important for different domains of children's health and wellbeing [@riaziChildrenIndependentMobility2018]. There is also sufficient evidence in the literature linking the association between AST and CIM [@laroucheRelationshipsChildrenIndependent2020; @mitraIndependentMobilityMode2013], particularly in boys [@schoeppeAssociationsChildrenIndependent2014]. The gender disparity has also been noted in other papers regarding CIM [@marziSocialPhysicalEnvironmental2018; @marziInterventionsAimingPromote2020] with recommendations being made for interventions to specifically target girls to boost their mobility within their neighborhood [@schoeppeSociodemographicFactorsNeighbourhood2015]. CIM offers other benefits to adolescents such as increasing traffic and safety skills, boosting spatial awareness when navigating public spaces, and providing more opportunity for social interaction with peers [@schoeppeAssociationsChildrenIndependent2014]. What is less clear is how CIM plays into the consideration of policymakers when they act on the objective of improving AST. 

In the case of Canada... _review a few prominent Canadian studies on AST and CIM in more detail: Riazi et al., 2019; Mammen et al., 2012 & 2014; Rothman et al., 2021_

The correlates and effective interventions of AST and CIM are important knowledge for policymakers because they identify points of intervention, as well as potential benefits, that ought to be communicated to the public to build support for new planning paradigms. Framing analysis is one method to analyze how particular issues are framed to groups of people, for instance parents or educators who might be inclined to support AST. It attempts to understand how information presented from a "communicator" leads the "receiver" to a desired response [@reynardGrowthResilienceHow2021]. In Reynard et al., [-@reynardGrowthResilienceHow2021] framing analysis was applied to review municipal policies addressing climate change in four western Canadian cities. The authors determined that most issues are framed favoring merely a tinkering of the status quo as opposed to pushing for real change. The way these policy issues are framed is important to understand because it plays a role in either altering or preserving the existing social perceptions. In the case of AST and CIM in Canada, Riazi et al. [-@riaziCorrelatesChildrenIndependent2019] state: "it will be vital for interventions to target modifiable factors, including children's and parents' perceptions of their social environment." Parents play the important role of "gatekeeper" by either granting or restricting CIM licenses, meaning whether children can travel alone [@sharminAssociationBuiltEnvironment2017]. Framing is also important because both walking and cycling are often targeted together, whereas evidence shows that distinct interventions should target each separately [see @helbichChildrenSchoolCommuting2017], which has implications for how municipalities and schools aim to address this issue. For these reasons, the framing of active school travel should be explored and considered given its potential to influence and incentivize behaviour change.

The aim of this paper is to consider how AST, STP, and CIM are framed in the province of Ontario in Canada by varying stakeholders involved in these initiatives. Specifically, municipal governments, public health units, transportation consortium, and school boards who work together to promote active school travel. _Describe in further detail once procedure for analysis is conceptualized_

## Case Study: Ontario, Canada

In Ontario, active school travel initiatives spread across the province by the 2000s [@ontarioactiveschooltravel] and were attempted by individual schools independent of a coordinated movement. Such one-off efforts, particularly those targeting education or promotional initiatives, may only prove to provide AST in the short term [@chillonSystematicReviewInterventions2011]. At about the same time, a concept called School Travel Planning (STP) was developed in the United Kingdom [@greencommunities2007]. STP offered an opportunity for key local stakeholders such as schools, school boards, and municipalities to make tangible changes to both the social and physical environment to encourage AST among their students that can be sustained in the long term. However, it was not until 2007-2009 that Green Communities Canada (GCC), a non-profit organization, began adapting and delivering a universal STP framework. This initiative followed their publication on the _Review of International School Travel Planning Best Practices_ in 2007, which included the initial pilot in the United Kingdom, and others in New Zealand, Australia, and United States. Under GCC’s framework, a Canadian pilot intervention was trialed at twelve schools across four provinces [@buliungSchoolTravelPlanning2011a]. The results of the pilot convinced the government of the Province of Ontario to issue a grant which culminated in the development of the program _Ontario Active School Travel_ (OAST), formerly known as Active & Safe Routes to School, headed by GCC. 

As of 2021, OAST continues its work by providing resources for interested stakeholders and funding projects across Ontario led by collaborative groups involving school boards, municipalities/regions, and regional transportation consortiums. The latter is a unique group of entities sanctioned by the Ontario Ministry of Education in 2006. These entities are a collaboration between regions and school boards whose objective is to deliver more efficient and effective transportation services to its area [@ministryeducation2006].

# Methods

## Procedure

## Data Analysis

# Results

# Discussion

## Limitations

## Conclusion

# Implications for School Health

Schools are an influential contributor to AST and STP efforts in Canada.
